name: Rust

on:
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    environment: workflows
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          override: true
      - name: Build
        run: cargo build --release
      - name: Test
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSW: ${{ secrets.PASSW }}
        run: cargo test --release
